# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  BeEngine_config = debug

else ifeq ($(config),release)
  BeEngine_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := BeEngine

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

BeEngine:
ifneq (,$(BeEngine_config))
	@echo "==== Building BeEngine ($(BeEngine_config)) ===="
	@${MAKE} --no-print-directory -C . -f BeEngine.make config=$(BeEngine_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f BeEngine.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   BeEngine"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"